name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_CRASH_REPORTS: 0
        with:
          start: npm run start:dist
      - uses: actions/upload-artifact@master
        with:
          name: website
          path: dist
  deploy:
    needs: tests
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
          path: dist
      - run: ls dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
