name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_CRASH_REPORTS: 0
        with:
          build: npm run build
          start: npm run start:dist
  deploy:
    needs: tests
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
